In [1]:
import numpy as np

In [3]:
np.empty(3)

array([1.17079111e-311, 0.00000000e+000, 4.94065646e-324])

In [4]:
np.empty((3,5))

array([[0.000000e+000, 0.000000e+000, 0.000000e+000, 0.000000e+000,
        0.000000e+000],
       [0.000000e+000, 0.000000e+000, 0.000000e+000, 0.000000e+000,
        0.000000e+000],
       [0.000000e+000, 0.000000e+000, 0.000000e+000, 0.000000e+000,
        3.917925e-317]])

In [7]:
a = np.empty((4,5), dtype = 'int')

In [8]:
a

array([[4128860, 6029375, 3801155, 5570652, 6619251],
       [7536754, 4456540, 4980805, 6029388, 7340097],
       [4456560, 7602273, 6029409, 7274572, 6357091],
       [6029420, 6619220, 7340141,       0,       0]])

In [9]:
a.ndim

2

In [10]:
a.size

20

In [11]:
a.shape

(4, 5)

In [12]:
a.dtype

dtype('int32')

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.eye(5,8, dtype = 'int')

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0]])

In [17]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((8,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.array((5,5))

array([5, 5])

In [22]:
np.full(10,8)

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [23]:
np.full((8,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [26]:
a = np.array([1,2,3,4,5,6])

In [29]:
a.sum()

21

In [30]:
a.mean()

3.5

In [31]:
a.min()

1

In [32]:
a.max()

6