In [1]:
import numpy as np

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a[2]

2

In [5]:
a = np.arange(5,15)

In [6]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
a[0]

5

In [10]:
a[-1]

14

In [12]:
a[::2]

array([ 5,  7,  9, 11, 13])

In [13]:
a =np.full((5,5),6)

In [14]:
a

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [15]:
a[0]

array([6, 6, 6, 6, 6])

In [16]:
a[-1]

array([6, 6, 6, 6, 6])

In [17]:
a[::2]

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [19]:
a =np.array([[1,2,3,4,5],[6,7,8,9,20],[21,22,23,24,25]])

In [20]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 20],
       [21, 22, 23, 24, 25]])

In [21]:
a[1,3]

9

In [22]:
a = np.full((5,5),8)         

In [23]:
a

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [25]:
a[1:3,2:4]

array([[8, 8],
       [8, 8]])

In [26]:
a = np.arange(5)

In [27]:
a

array([0, 1, 2, 3, 4])

In [32]:
a = np.array([[1,2,3,4,5], [4,5,6,7,8], [7,8,9,10,11], [7,6,5,4,3]])

In [33]:
a

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11],
       [ 7,  6,  5,  4,  3]])

In [34]:
a[3,3]

4

In [37]:
a[1:3,2 ]

array([6, 9])

In [38]:
a[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [40]:
# arithmetic operations happens elementwise/indexwise

In [41]:
a = np.arange(10)

In [42]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [47]:
a = np.arange(2,5)

In [48]:
b = np.arange(3,6)

In [49]:
a

array([2, 3, 4])

In [50]:
b

array([3, 4, 5])

In [51]:
a+b

array([5, 7, 9])

In [52]:
a = np.arange(3,8)

In [53]:
a[[True, True, False, False, True]]

array([3, 4, 7])

In [54]:
a

array([3, 4, 5, 6, 7])

In [55]:
a > 3

array([False,  True,  True,  True,  True])

In [56]:
a = np.arange(2,15)

In [57]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True])