In [1]:
import numpy as np

In [2]:
np.array(2)

array(2)

In [3]:
a = np.array([1,2,3,4])

In [4]:
print(a)

[1 2 3 4]


In [5]:
b = np.array([1,2,3,4.9])

In [6]:
print(b)

[1.  2.  3.  4.9]


In [7]:
b = np.array([1.0,2.0,3.0,4.0], dtype = 'int')

In [8]:
print(b)

[1 2 3 4]


In [9]:
c = np.array([[1,2,3],[4,5,6]])

In [10]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a = np.array([1,2,3])


In [12]:
a

array([1, 2, 3])

In [13]:
a.dtype

dtype('int32')

In [14]:
a.ndim

1

In [15]:
a.shape

(3,)

In [16]:
a.size

3

In [17]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

In [18]:
b.dtype

dtype('float64')

In [19]:
b.ndim

2

In [20]:
b.size

6

In [22]:
b.shape

(2, 3)