In [1]:
import numpy as np

In [2]:
a = np.arange(1,10)

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a[[True, True, True, False, False, False, False, True, True]]

array([1, 2, 3, 8, 9])

In [5]:
a>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [6]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True, False])

In [7]:
a[a%2==0]

array([2, 4, 6, 8])

In [8]:
a[a<5]

array([1, 2, 3, 4])

In [9]:
a[(a>2) & (a<8)]

array([3, 4, 5, 6, 7])

In [10]:
a[(a%2==0)|(a%3==0)]

array([2, 3, 4, 6, 8, 9])

In [12]:
a = np.arange(50,101)

In [13]:
a

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [15]:
a[(a%5==0)&(a%10==0)]

array([ 50,  60,  70,  80,  90, 100])

In [16]:
a = np.arange(2,10)

In [17]:
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
newar = a.reshape(2,4)

In [19]:
newar

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [20]:
a = np.arange(24)

In [21]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
a = a.reshape(6,4)

In [23]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
a = a.reshape(8,3)

In [25]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [26]:
a= np.arange(10)

In [27]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a.sum()

45

In [29]:
a.min()

0

In [31]:
a.std()

2.8722813232690143

In [32]:
a.var()

8.25